<a href="https://colab.research.google.com/github/tobschaffer/vorlesungen-tcc/blob/master/LA04_Lineare_Algebra_Eigenwerte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LA04 Lineare Algebra - Eigenwerte

### Definition: Eigenwert

> Ist $A \in \mathbb{R}^{n x n}$ eine quadratische nxn -Matrix, dann heißt $\lambda \in \mathbb{R}$ **Eigenwert** von $A$ wenn es einen Vektor $v \in \mathbb{R}^n$ ($v \neq 0$) gibt, so dass gilt:
>  
>$$
A \cdot v = \lambda \cdot v
$$
>  
> Das heißt $A$ wirkt auf $v$ wie die skalara Multiplikation mit $\lambda$. In Richtung $v$ findet durch Anwendung der linearen Abbildung $A$ also **keine** Richtungsänderung, sondern nur eine Längenänderung statt. Man nennt $v$ dann einen **Eigenvektor** zu $\lambda$.
  

Bemerkungen:

- Eigenvektoren sind nicht eindeutig, z.B. ist jedes skalare Vielfache eines Eigenvektors wieder ein Eigenvektor zum gleichen Eigenwert.
- Für eine gegebene Matrix $A$ ist nicht jeder reelle Wert ein Eigenwert, d.h. es gibt nicht für jeden skalaren Wert in $\mathbb{R}$ einen ensprechenden Eigenvektor. Im Gegenteil gibt es zu einer gegebenen nxn-Matrix $A$ nur **wenige** Eigenwerte (höchstens n viele verschiendene).
- Eine Matrix kann verschiendene Eigenwerte haben. Mit Vielfachheit kann eine nxn-Matrix **höchstens n reelle** Eigenwerte haben.
- Symmetrische nxn-Matrizen haben (mit Vielfachheit) **genau n relle** Eigenwerte.

Beispiel:  

$A = \begin{pmatrix} 3 & -1 \\ -2 & 4 \end{pmatrix} \in \mathbb{R}^{2 x 2}$ ist eine quadratische 2x2-Matrix. Sie hat den Eigenwert 2, denn für $v = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$ gilt: 

$$
A \cdot v = \begin{pmatrix} 3 & -1 \\ -2 & 4 \end{pmatrix} = \begin{pmatrix} 2 \\ 2 \end{pmatrix} = 2 \cdot v
$$  

Damit ist $v$ *ein* **Eigenvektor** zum **Eigenwert** 2 (beachte, $v$ ist nicht *der* Eigenvektor zum Eigenwert 2, da es zu jedem Eigenwert stets unendlich viele Eigenvektoren gibt).

In [0]:
'''
Obige Berechnung mit numpy durchführen
'''
# NumPy Modul für numerische Berechnungen importieren
import numpy as np

'''
Mehrdimensionale Arrays (z.B. auch Matrizen) werden als np.array angelegt.
Diese sind hirarchisch aus eindimensionalen Arrays [a, b, c, ...] aufgebaut.
'''

# Matrix A anlegen
A = np.array([[3, -1], [-2, 4]])

'''
Strings werden in Anführungszeichen gesetzt: "text text" oder 'text text'.
Sogenannte f-Strings (ab Python 3) erlauben eine kompakte Schreibweise formatierter Strings:
f"text text {variable}"
\n ist die Escape Sequenz für einen Zeilenumruch
'''

# Matrix A anzeigen
print(f"A = \n{A}\n")

'''
Achtung, np.array([[1], [1]]) bildet einen Spaltenvektor, 
np.array([1, 1]) bildet einen Zeilenvektor
'''

# Vektor v anlegen
v = np.array([[1], [1]])

# Vektor v anzeigen
print(f"v = \n{v}\n")

'''
Achtung, für die Matrix Multiplikation immer array.dot() benutzen
A*v liefert z.B. ein anderes Ergebnis (komponentenweise Mult.)
'''

# Matrix-Multiplukation durchführen
print(f"Av = \n{A.dot(v)}")

A = 
[[ 3 -1]
 [-2  4]]

v = 
[[1]
 [1]]

Av = 
[[2]
 [2]]


### Aufgabe LA04-A1

- Zeige: $w = \begin{pmatrix} -5 \\ -5 \end{pmatrix}$ ist ein Eigenvektor zum Eigenwert 2 für die Matrix $A = \begin{pmatrix} 3 & -1 \\ -2 & 4 \end{pmatrix}$
- Zeige: $w = \begin{pmatrix} 1 \\ -5 \end{pmatrix}$ ist **kein** Eigenvektor der Matrix $A = \begin{pmatrix} 3 & -1 \\ -2 & 4 \end{pmatrix}$


### Aufgabe LA04-A2

Zeige, dass $u = \begin{pmatrix} 10 \\ 3 \\ -11 \end{pmatrix}$, $v = \begin{pmatrix} -1 \\ 0 \\ 1 \end{pmatrix}$ und $w = \begin{pmatrix} 4 \\ 3 \\ -7 \end{pmatrix}$ Eigenverktoren der Matrix $A = \begin{pmatrix} 2 & -3 & 1 \\ 3 & 1 & 3 \\ -5 & 2 & -4 \end{pmatrix}$ sind und bestimme die zugehörigen Eigenwerte. 

### Aufgabe LA04-A3

Konstruiere eine 2x2-Matrix mit den Eigenwerten $2$ und $3$.

### Definition: Charakteristisches Polynom einer Matrix

>Ist $A \in \mathbb{R}^{nxn}$ eine quadratische Matrix, dann bezeichnet man das Polynom, das durch die folgende Determinantenbildung entsteht
>
>$$
P(\lambda) = \det(A-\lambda \cdot E)
$$
>
>als **charakteristisches Polynom** von $A$. Die entsprechende Polynomgleichung 
>
>$$
\det(A-\lambda \cdot E) = 0
$$
>
>bezeichnet man als **charakteristische Gleichung** von $A$.  
>
>Dabei bezeichnet $E$ die nxn-Einheitsmatrix.



Beispiel:

Das charakteristische Polynom $P(\lambda)$ von $A = \begin{pmatrix} 3 & -1 \\ -2 & 4 \end{pmatrix} \in \mathbb{R}^{2 x 2}$ ist:  

$$
\begin{split}
P(\lambda) & = \det(A - \lambda \cdot E) \\
& = \det\begin{pmatrix} 3 - \lambda & -1 \\ -2 & 4 - \lambda \end{pmatrix} \\
& = (3 - \lambda)(4 - \lambda) - (-2)(-1) \\
& = \lambda^2 - 7\lambda + 10
\end{split}
$$



### Berechnung der Eigenwerte einer Matrix

>Die Eigenwerte einer Matrix $A$ erhält man als Nullstellen ihres charakteristischen Polynoms.  
>
>Die Eigenvektoren zu einem Eigenwert $\lambda$ erhält man als Lösungsmenge des linearen Gleichungssystems $A - \lambda E = 0$.

### Aufgabe LA04-A4

a) Bestimme die Eigenwerte der Matrix $A = \begin{pmatrix} 2 & 1 & 2 \\ 1 & 2 & 2 \\ 1 & 1 & 3 \end{pmatrix}$. Bestimme zu jedem Eigenwert mindestens einen Eigenvektor.

b) Bestimme die Eigenwerte der Matrix $B = \begin{pmatrix} 2 & 0 & -2 \\ 0 & 4 & 0 \\ -2 & 0 & 5 \end{pmatrix}$.

In [0]:
'''
Ergebnis aus Aufgabe LA04-04 numerisch verifizieren
'''

import numpy as np

A = np.array([[2, 0, -2], [0, 4, 0], [-2, 0, 5]])

# Eigenwerte und Eigenvektoren berechnen (numerische Berechnung)
[eigenvalues, eigenvectors] = np.linalg.eig(A)

# Eigenwerte anzeigen
print(eigenvalues)

[1. 6. 4.]


### Aufgabe LA04-A5

Bestimme die Eigenwerte der Matrix $C = \begin{pmatrix} 1 & 2 & 1 \\ 6 & -1 & 0 \\ -1 & -2 & -1 \end{pmatrix}$ und verifiziere das Ergebnis numerisch.

### Weiterführende Literatur

Bitte Wikipedia Eintrag dazu lesen:  

https://de.wikipedia.org/wiki/Eigenwertproblem

